name: sdapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  http: ^1.2.1
  file_picker: ^8.0.5 # Added for file picking
  intl: ^0.19.0 # Added for date formatting
  flutter_datetime_picker: ^1.5.1 # Added for date picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/login_background.png
